Imagestream generator
sclorg/ci-scripts pull request #119
Opened 2024-01-22 08:56 UTC by zmiklank

This is still a Work in Progress. Support for latest imagestreams is not yet implemented. The config for this script is to be given as its first argument and should have following format:

```
$ cat imagestreams.yaml
---
- name: postgresql
  pretty_name: PostgreSQL
  description: Provides a PostgreSQL APP_VERSION database on DISTRO_NAME. For more information about using this database image, including OpenShift considerations, see https://github.com/sclorg/postgresql-container/blob/master/README.md.
  imagestream_files:
  - filename: postgresql-rhel.json
    latest: "15-el8"
    distros:
      - name: RHEL 8
        app_versions: [12, 13, 15]
        image_template: "registry.redhat.io/rhel8/postgresql-APP_VERSION:latest"

      - name: Ephemeral
        app_versions: [10]
        image_template: "registry.redhat.io/rhscl/postgresql-APP_VERSION-rhel7:latest"
```  
  This shall be documented before a merge.

2024-01-23 13:40 UTC, zmiklank commented
The full postgresql imagestream.yaml config can be seen here:
https://github.com/sclorg/postgresql-container/pull/549

2024-01-24 13:59 UTC, zmiklank commented on ocp-stream-generator/distribution_data.py
> +latest_description = "\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version available on OpenShift, including major version updates."
Can latest stream move between RHEL major versions too?

2024-01-24 14:02 UTC, zmiklank commented on ocp-stream-generator/distribution_data.py
> +          "UBI 8": "registry.redhat.io/ubi8/postgresql-APP_VERSION:latest",
```suggestion
          "UBI 8": "registry.redhat.io/ubi8/APP_NAME-APP_VERSION:latest",
```

2024-01-25 10:58 UTC, phracek commented on ocp-stream-generator/distribution_data.py
> +latest_description = "\n\nWARNING: By selecting this tag, your application will automatically update to use the latest version available on OpenShift, including major version updates."
yes.

2024-01-25 11:09 UTC, phracek requested changes
I am thinking if this repository is the correct one.

We need a test suite for this !!! So we know what is exact format.

We generate the source for customers and we should now if everything is working properly.

What about to move it to container-common-scripts where is test suite already present? THis repository does not contain any test suite.

Or we can use `container-ci-suite` later on where test are already DONE in OpenShift 4 cluster.

And the test suite would test random imagestream directly in OpenShift.

2024-01-25 11:09 UTC, phracek commented on ocp-stream-generator/stream_generator.py
> +    def get_data(self):
This could be done as `@property`:

```
class Loaded:
   _config = None

   @property
   def self.config:
      if not self._config:
         with open(name,'r') as file:
            self._config = yaml.safe_load(file)[0]
      return self._config

2024-01-25 11:09 UTC, phracek commented on ocp-stream-generator/stream_generator.py
> +            _image = images[self.distro_name].replace("APP_VERSION", str(self.version))
```suggestion
            _image = images[self.distro_name].replace("APP_VERSION", str(self.version)).replace("APP_NAME", app_name)
```

2024-01-25 11:09 UTC, phracek commented on ocp-stream-generator/stream_generator.py
> +        _description = desc.replace("APP_VERSION", str(self.version))
```suggestion
        _description = desc.replace("APP_VERSION", str(self.version)).replace("DISTRO_NAME", self.distro_name)
```

2024-01-25 11:09 UTC, phracek commented on ocp-stream-generator/stream_generator.py
> +        _header['metadata'] =  { "name": data.app_name,"annotations": {"openshift.io/display-name": data.app_pretty_name}}
Please format this dictionary.

2024-01-25 11:09 UTC, phracek commented on ocp-stream-generator/stream_generator.py
> +        _header = {}
Why with `_`?

2024-02-05 09:03 UTC, zmiklank commented on ocp-stream-generator/stream_generator.py
> +        _header = {}
I named all function specific variables with underscore.

2024-02-13 13:13 UTC, zmiklank commented
I have added some unit tests.
I am not sure, why the github action does not run - it is possible that the yaml file for it needs to be in master branch.
Integration tests will be needed too - they should probably be in repositories for container images. These integration tests should test import of the imagestreams to the OCP.

Please re-review @phracek, @pkubatrh.

2024-02-14 13:20 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +            return str(self.version) + "-" + abbreviations[self.distro_name]
What about to use syntax like `f"{str(self.version)}-{abbreviations[self.distro_name]}"`

2024-02-14 13:22 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        _header['kind'] = "ImageStream"
The same here.

2024-02-14 13:23 UTC, phracek commented on ocp-stream-generator/tests/test_json_builder.py
> +    result = {'spec': {'tags': [{'name': '1-el8', 'annotations': {'openshift.io/display-name': 'Test 1 (RHEL 8)', 'openshift.io/provider-display-name': 'Red Hat, Inc.', 'description': 'test descripti
This can be pytest fixture and the dictionary can be stored in the file.

2024-02-14 13:28 UTC, zmiklank commented on .github/workflows/python-tests.yml
> +        tox_env: py311
The generator will run on some ubuntu runner from GitHub. I does not really see any reason why using more pythons for testing. Why do you think we should use more python versions?

2024-02-14 13:29 UTC, zmiklank commented on .github/workflows/python-tests.yml
> +...
That is optional syntax of YAML:


All YAML files (regardless of their association with Ansible or not) can optionally begin with --- and end with .... This is part of the YAML format and indicates the start and end of a document.[0]

[0] https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

2024-02-16 15:37 UTC, zmiklank commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +class YamlLoader:
That because I want the code to be modular and easily extendible.

2024-02-19 12:56 UTC, zmiklank commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        _latest_distro = self.obtain_distro_for_latest(file['latest']);
It is a Python convention (even though I am not sure I used it as it was designed).
You can read more about it, e.g., here: https://pep8.org/#descriptive-naming-styles

2024-02-19 14:03 UTC, zmiklank commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +            return str(self.version) + "-" + abbreviations[self.distro_name]
Do you see any advantages in using string formatting like in you example above?

2024-02-20 08:42 UTC, zmiklank commented on ocp-stream-generator/tests/test_json_builder.py
> +    result = {'spec': {'tags': [{'name': '1-el8', 'annotations': {'openshift.io/display-name': 'Test 1 (RHEL 8)', 'openshift.io/provider-display-name': 'Red Hat, Inc.', 'description': 'test descripti
I have moved the result dictionaries to data file. I have not used python fixtures though. Can it be like this?

2024-02-20 08:42 UTC, zmiklank commented
> Please see my comments.

@phracek all comments should be addressed now.

2024-02-28 09:37 UTC, phracek commented on .github/workflows/python-tests.yml
> +...
ok, thank make sense this issue

2024-02-28 09:44 UTC, phracek requested changes
Only some issues.

2024-02-28 09:44 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +    def json_data(self):
json_data is misleading. It should be yaml_data.
And from python point of view. I would say to have `_data` instead of `data` as it is property.

2024-02-28 09:44 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +            return str(self.version) + "-" + abbreviations[self.distro_name]
I would say, prefered way.

2024-02-28 09:48 UTC, phracek requested changes
Some minor changes

2024-03-11 08:46 UTC, phracek approved these changes
LGTM. Thanks for this.

2024-03-11 08:46 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        _disp_name = f'{tag.app_pretty_name} {str(tag.version)}'
The same here

2024-03-11 08:57 UTC, merged