is generator: add possibility to generate custom tags, and to specify target dir
sclorg/ci-scripts pull request #125
Opened 2024-05-13 09:54 UTC by zmiklank

2024-05-14 12:45 UTC, phracek requested changes
Thanks for this pull request.

It would be nice to add into description also some examples, how the imagestream.yaml file is going to be changed.

The code is pretty hard to read. I would prefer to have one class with 
one or two methods. Many fields are repeated in CustomTag and LatestTag classes.

2024-05-14 12:45 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +    app_version: int
Why the version was renamed to app_version?

2024-05-14 12:45 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        self.category = header["category"]
This is the same as for CustomTag as for LatestTag, header["name"] as well.
Is it really needed to add so much Tag classes to this script?

2024-05-14 12:45 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        self.stream_name = "latest"
What about adding into Tag class method like set_stream_name_to_latest?

2024-05-14 12:45 UTC, phracek commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        self.app_pretty_name = header["pretty_name"]
The same for CustomTag

2024-05-14 12:50 UTC, zmiklank commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +    app_version: int
To align with the rest of the code and with the yaml configuration file, where we use app_version and app_versions too.

2024-05-14 12:53 UTC, zmiklank commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        self.category = header["category"]
Yes it is, because every class sets its members in different way.
What I can do is to create fourth class Tag, from which LatestTag, CustomTag and StandardTag could inherit the constructor, which could set the few members that are set the same for all the classes. Not sure if that isn't overkill, but it will decrease the code duplicates.

2024-05-14 12:55 UTC, zmiklank commented on ocp-stream-generator/ocp-stream-generator/stream_generator.py
> +        self.stream_name = "latest"
That would require new `if` condition.
Object oriented programming is imo great in letting you avoid many `if`s when using inheritance, which imo makes the code more readable.

2024-05-20 12:00 UTC, phracek approved these changes
Thanks for finishing this PR. LGTM. Test are passing.

2024-05-20 12:00 UTC, merged