upload-diff scripts
sclorg/ci-scripts pull request #28
Opened 2021-03-16 12:18 UTC by phracek

This pull request moves scripts from `rhscl-container-ci` repo into this repo.
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

2021-03-16 14:05 UTC, hhorak requested changes
Few comments inline.. Except that, I'd maybe consider renaming at least one of the files `upload_diff.py` and `upload_diff.sh` -- the difference in extension only leads to conclusion that the scripts do the same, while in reality one is a wrapper for another.. What about adding `github` to the `upload_diff.py` name since it specifically handles github API and maybe `jenkins` to the `upload_diff.sh` as it specifically works with environment variables defined by Jenkins.

2021-03-16 15:07 UTC, phracek commented on jenkins_ci/upload_diff.py
> +#!/usr/bin/python
Let me clarify it. I guess, some libraries are missing in our Jenkins CI environment. Like `python3-requests`.

2021-03-16 15:07 UTC, phracek commented on jenkins_ci/upload_diff.py
> +commit_url = sys.argv[1]
I will rename it by the next commit. Thanks.

2021-03-17 10:28 UTC, phracek commented on jenkins_ci/upload_diff.py
> +commit_url = sys.argv[1]
In the future, I would like to create a class like JenkinsCI that will do all stuff and we do not need more Python files.

2021-03-17 10:28 UTC, phracek commented on jenkins_ci/upload_diff.py
> +commit_url = sys.argv[1]
Of course based from the input.

2021-03-17 10:31 UTC, phracek commented
@hhorak Hopefully I have addressed all issues. PTAL on it one more time. Thank you for the review, though.

2021-03-18 15:19 UTC, hhorak requested changes
The checking of args does not seem to be working (but didn't test it).

2021-03-18 15:19 UTC, hhorak commented on jenkins_ci/github_gist_upload_diff.py
> +if commit_url == "":
I think it will not get to this line if there are no arguments, I'd guess there is an IndexError exception instead 3 lines above. What about using try/except here instead?

2021-03-18 15:24 UTC, phracek commented on jenkins_ci/github_gist_upload_diff.py
> +if commit_url == "":
From the Jenkins CI point of view, this is not possible. All arguments are present. But you are right to be 100% sure, that all arguments are present. I will fix it.

2021-03-19 10:06 UTC, phracek commented on jenkins_ci/github_gist_upload_diff.py
> +if commit_url == "":
@hhorak I have completely changed the variable process. argparse is used instead of sys.argv. This is the pythonic better approach.

2021-03-22 10:47 UTC, hhorak approved these changes
LGTM now, thanks, good work!

2021-03-22 10:55 UTC, merged