SCLORG sanity checks over all repositories
sclorg/ci-scripts pull request #75
Opened 2022-11-11 10:19 UTC by phracek

The aim of this daily checker is:

* detect if .exclude and Dockerfile are present and think about usage .devel repo because of version is not tested
* detect if .exclude file is present and Dockerfile not
* detect if .devel_repo is present and GA is not reached.
* 
Signed-off-by: Petr "Stone" Hracek <phracek@redhat.com>

2022-11-14 10:00 UTC, zmiklank commented
Sorry, I am missing some context. What is this "daily checker" please?

2022-11-22 15:17 UTC, hhorak commented on daily_tests/sclorg_sanity_tests.py
> +    def create_tmp_dir(self):
I don't see the tmpdir is cleaned -- is it staying created on purpose? There's been effort cleaning after images' tests, so maybe this test might clean after itself as well, alternatively `--no-clean` option can be added if there is a reason to keep the working dirs for further analysis.

2022-11-22 15:21 UTC, hhorak commented on daily_tests/sclorg_sanity_tests.py
> +from git.exc import GitCommandError
Some of the modules are likely not in the default set of components -- shouldn't we have either one common requirements.txt, or better include all scripts into a separate directory (with proper requirements.txt and README.md for the single tool) and then only symlink in the daily_tests dir? (just an idea)

2022-11-22 15:23 UTC, hhorak commented on daily_tests/sclorg_sanity_tests.py
> +    sanity_checker = SclOrgSanityChecker()
We should have some comment that explains what the tool does. Alternatively, even when the tool does not accept options at this point, we can use argparese and have standardized `-h`, `--help` with a reasonable explanation. (just an idea, not a requirement to implement it this way)

2022-11-22 15:25 UTC, hhorak commented on daily_tests/sclorg_sanity_tests.py
> +                    sanity_ok = False
Do I understand correctly it only prints list of repos where an issue was detected? Maybe we can report what kind of issue right away, so it's more clear from the mail...

2022-11-22 15:26 UTC, hhorak commented
Thanks for the initial work, this is gonna be useful. Several comments in-line.

2022-11-23 10:59 UTC, zmiklank requested changes
Thank you for working on the checker.
Please see my comments. Also, would it be possible to make the commit message more verbose, so we will know in the future what the commit does?

Another thing: where will this script run? Would it be triggered periodically via GitHub Actions? Or do you have something else in mind?

2022-11-23 10:59 UTC, zmiklank commented on daily_tests/sclorg_sanity_tests.py
> +    ("s2i-base-container", "s2i-base"),
I there any reason why the base container has the `s2i` prefix when others do not have it?
```suggestion
    ("s2i-base-container", "base"),
```

2022-11-23 10:59 UTC, zmiklank commented on daily_tests/sclorg_sanity_tests.py
> +        print(f"Check .exclude file for {ver}.")
```suggestion
        print(f"Check .devel_repo file for {ver}.")
```

2022-11-23 10:59 UTC, zmiklank commented on daily_tests/sclorg_sanity_tests.py
> +            dockerfile = self.tmp_path_repo / ver / f"Dockerfile.{os_ver}"
I see a lot of duplicity in `check_devel_repo_file` and ` check_exclude_file`. Could not it be done something with it?

2022-11-23 13:32 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +from git.exc import GitCommandError
Make sense to me. I will drive it.

2022-11-23 13:32 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +    sanity_checker = SclOrgSanityChecker()
Good idea.

2022-11-23 13:34 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +URL = "https://url.corp.redhat.com/application-streams-yaml"
The url contains information about lifestream EOL and GA information.

2022-11-23 13:35 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +        send_to = "phracek@redhat.com"
It is planned to have all containerization and some Apps folks. I will update it.

2022-11-24 07:27 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +            dockerfile = self.tmp_path_repo / ver / f"Dockerfile.{os_ver}"
this is fixed by commit https://github.com/sclorg/ci-scripts/pull/75/commits/a4ad5e6019012baed5db30ff9b7f128a4bff869f

2022-11-24 07:27 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +            dockerfile = self.tmp_path_repo / ver / f"Dockerfile.{os_ver}"
THis is fixed by commit https://github.com/sclorg/ci-scripts/pull/75/commits/a4ad5e6019012baed5db30ff9b7f128a4bff869f

2022-11-24 07:27 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +URL = "https://url.corp.redhat.com/application-streams-yaml"
This is fixed by commit https://github.com/sclorg/ci-scripts/pull/75/commits/a4ad5e6019012baed5db30ff9b7f128a4bff869f

2022-11-24 07:28 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +    sanity_checker = SclOrgSanityChecker()
Fixed by https://github.com/sclorg/ci-scripts/pull/75/commits/a4ad5e6019012baed5db30ff9b7f128a4bff869f

2022-11-24 07:28 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +from git.exc import GitCommandError
Fixed by https://github.com/sclorg/ci-scripts/pull/75/commits/35c358e11431045df368d373a2b9661819e11a77

2022-11-24 07:29 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +                    sanity_ok = False
It is done during the print like:

```bash
--- 5.34:
File .exclude-c9s is present in and Dockerfile.c9s as well. The version 5.34 is not tested.
Please think about usage '.devel-repo-c9s' or check if image does not reach EOL.
```

2022-11-24 07:31 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +        send_to = "phracek@redhat.com"
Fixed by commit https://github.com/sclorg/ci-scripts/pull/75/commits/c006f9027ed5aba80b0a30c065a179d5253a2234

2022-11-24 07:32 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +    def create_tmp_dir(self):
It is fixed at the end of run_check function https://github.com/sclorg/ci-scripts/pull/75/files#diff-31589a09c0dea50a4a46f7ec84601ba88c0f9c5bb220755146cfbaafbc89d5c9R234

2022-11-24 08:56 UTC, hhorak commented on daily_tests/sclorg_sanity_tests.py
> +        self.send_email(failed_repos=failed_repos, result=global_result_flag)
I even think the sending itself could be optional -- sometimes one can run the test locally (even repeatedly) to check whether there are still some issues and in that case, sending mail is not desired.

2022-11-24 10:51 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +        self.send_email(failed_repos=failed_repos, result=global_result_flag)
I will do it.

2022-11-24 12:42 UTC, phracek commented on daily_tests/sclorg_sanity_tests.py
> +        self.send_email(failed_repos=failed_repos, result=global_result_flag)
Fixed by https://github.com/sclorg/ci-scripts/pull/75/commits/62139112baf0989a8e4eaf819cace85589397706

2022-11-24 13:02 UTC, zmiklank commented on daily_tests/sclorg_sanity_tests.py
> +class GitHubSanityChecker(object):
nickpick: I found the original name more fitting (SclOrgSanityChecker.)

2022-11-24 13:02 UTC, zmiklank approved these changes
One nitpick, esle LGTM.

2022-11-24 13:24 UTC, phracek commented
Let's get merge it and deploy it. The first time it will be executed manually and the next run will be each Monday at 8 am.

2022-11-24 13:24 UTC, merged