Add script to update Quay image description
sclorg/ci-scripts pull request #85
Opened 2023-05-15 10:07 UTC by adobes1

To run this script locally:
1. Ensure that your current working directory is the root directory of the container whose description you want to update
2. Run the following: 
```
REGISTRY_TOKEN=<quay-registry-token>  \
IMAGE_NAME=<quay-image-name> \
REGISTRY_NAMESPACE=<quay-registry-namespace> \
DOCKER_CONTEXT=<build-context> \
GITHUB_REPO=<container-repo-github-name> \
<path-to-this-script>
```
Eg.
```
REGISTRY_TOKEN=<quay-registry-token >  \
IMAGE_NAME=postgresql-15-c9s \
REGISTRY_NAMESPACE=sclorg \
DOCKER_CONTEXT=15 \
GITHUB_REPO=postgresql-container \
<path-to-this-script>
```

2023-10-05 07:53 UTC, phracek commented
I have tried it but I received an error like:

```bash
FORBIDDEN
{"error": "CSRF token was invalid or missing."}
Unauthorized access
```

2023-10-05 08:06 UTC, phracek commented
Maybe login in script is missing?

2023-10-05 08:15 UTC, phracek commented
@adobes1 Please move the script to either daily_tests or directly to 'root'. But root would be better.

2023-10-05 12:26 UTC, phracek commented on jenkins_ci/update_quay_description.py
> +    token = os.environ["REGISTRY_TOKEN"] # Quay token
This should be `QUAY_IMAGE_UPDATE_DESC`

2023-10-05 13:21 UTC, phracek commented on jenkins_ci/update_quay_description.py
> +    errors = {400: "Bad Request",
I would prefer to use dictionary in style like:
```python
errors = {
   400: "Bad Request",
   401 ...
}
```

2023-10-05 13:25 UTC, phracek requested changes
Thank you for this pull request. It helps us to update description in all quay.io repository.
Perfect work, only some changes from my point of view.

2023-10-05 13:25 UTC, phracek commented on jenkins_ci/update_quay_description.py
> +                if i + 3 >= len(lines):
The number 3 can be a variable. With comment why it is used.

2023-10-05 13:25 UTC, phracek commented on jenkins_ci/update_quay_description.py
> +    api_request_path = f"https://quay.io/api/v1/repository/{registry_namespace}/{image_name}"
This could be a variable with all capitals at the beginning of this script.

2023-10-05 13:25 UTC, phracek commented on jenkins_ci/update_quay_description.py
> +    headers = {"Content-Type": "application/json",
This is dictionary. Like I was mentioned before.

2023-10-05 13:25 UTC, phracek commented on jenkins_ci/update_quay_description.py
> +    return r.status_code
What about to check everything here, including status and return only 'True' or 'False'?

2023-10-05 13:25 UTC, phracek commented on jenkins_ci/update_quay_description.py
> +    if len(readme_as_list) > 100:
This can be part of `load_readme_as_list`.
Only return None or String.

2023-10-05 13:41 UTC, zmiklank requested changes
Thank you for your work!

2023-10-05 13:41 UTC, zmiklank commented on jenkins_ci/update_quay_description.py
> +                return lines[i + 3:]
Adam already explained to me that these lines are here in order to not include first few sentences from README in quay.io description, as they contain information about various distributions of the image.

However the "Description" do not match all readmes, e.g., postgresql uses "Overview" instead of "Description".
Moreover, I think this design can be broken when some other line before the correct "Description" starts with word "Description."

I suggest dropping this feature entirely and publish the readme as whole or find a more generic mechanism. Other option could be to remove this section from the readmes entirely, as I think they are not really needed and should be included in the top-most readme. However, this would require many changes in many repositories.

2023-10-05 13:41 UTC, zmiklank commented on jenkins_ci/update_quay_description.py
> +    image_name = os.environ["IMAGE_NAME"] # Quay image name
Sourcing the variables needs to be changed based on where we decide to run this script.
If it is a part of build and push action then this PR would need to be moved against build-and-push repository and the variables would be sourced differently. I will need to look up how to use variables inside python scripts inside github actions, as until now I wrote everything in bash.

2023-10-05 13:41 UTC, zmiklank commented on jenkins_ci/update_quay_description.py
> +def escape_code_block(lines: List[str]):
Would be nice if there is come comment on why such function is needed. What the function does can be read from the code, but the intention behind it is not always clear.

2023-10-05 13:41 UTC, zmiklank commented on jenkins_ci/update_quay_description.py
> +    readme = "".join(readme_as_list)
I like that you put code blocks into functions making the code more readable. Do you think it would make sense to put this code section into some function too?

2023-10-31 11:25 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +    token = os.environ["REGISTRY_TOKEN"] # Quay token
Thank you, fixed

2023-10-31 11:26 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +    errors = {400: "Bad Request",
Fixed

2023-10-31 11:29 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +    if len(readme_as_list) > 100:
Thank you, fixed. I have renamed `load_readme_as_list` function to `load_readme` since it no longer returns list.

2023-10-31 11:31 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +                if i + 3 >= len(lines):
I have removed this whole section/feature, as per Zuzka's suggestions.

2023-10-31 11:32 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +    api_request_path = f"https://quay.io/api/v1/repository/{registry_namespace}/{image_name}"
Fixed

2023-10-31 11:34 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +    return r.status_code
Good idea, thank you. It should be fixed now.

2023-10-31 11:35 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +                return lines[i + 3:]
Thank you for this suggestion, you are right. I have removed this feature.

2023-10-31 11:37 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +def escape_code_block(lines: List[str]):
Thank you, I have added a comment explaining the purpose of this function.

2023-10-31 11:44 UTC, adobes1 commented on jenkins_ci/update_quay_description.py
> +    headers = {"Content-Type": "application/json",
Fixed

2024-01-23 07:52 UTC, phracek approved these changes
This looks good to me for first iteration. Let's merge it and fix errors later on.

2024-01-23 08:02 UTC, zmiklank commented
@phracek agreed, can we integrate this into build and push then?

2024-01-23 08:06 UTC, merged